export const PRODUCTS_ARR = [
  { id: 'kg10yda77k', label: 'Coffee Mocha', price: 9, recipe: ['imdcwgj7vcm', 'stshpszygl', 'wl2u7001i5j', '9vcjpxckykd'], image: '/assets/images/coffee-mocha.jpg' },
  { id: '3f51447su0z', label: 'Cappucino', price: 6, recipe: ['stshpszygl', 'wl2u7001i5j', '9vcjpxckykd'], image: '/assets/images/cappuccino.jpg' },
  { id: 'lm1poqe7rnk', label: 'Coffee Bombon', price: 6, recipe: ['p96tbt8ot8', '9vcjpxckykd'], image: '/assets/images/coffee-bombon.jpg' },
  { id: 'r6li6vtbcv', label: 'Coffee Melange', price: 7, recipe: ['2p03cnu269d', 'mrkz9n38qe'], image: '/assets/images/coffee-melange.jpg' },
  { id: '3xztjvoo1xp', label: 'Affogato', price: 7, recipe: ['9vcjpxckykd', '6v5dx6muodj'], image: '/assets/images/affogato.jpg' },
  { id: 'rpfv8zrmz3', label: 'Coffee Latte', price: 6, recipe: ['stshpszygl', 'wl2u7001i5j', '9vcjpxckykd'], image: '/assets/images/coffee-latte.jpg' },
  { id: 'sebm1fgjqs9', label: 'Coffee Breve', price: 6, recipe: ['stshpszygl', 'sf0zq2d35xk'], image: '/assets/images/coffee-breve.jpg' },
  { id: 'skp4fyyqyo', label: 'Flat White', price: 5, recipe: ['qz8lkb66q2o', '9vcjpxckykd'], image: '/assets/images/flat-white.jpg' },
  { id: 'quujtda2adl', label: 'Coffee Miel', price: 7, recipe: ['wl2u7001i5j', 'gnrrej15t3a', '8cak2bnj3wg', 'mrkz9n38qe'], image: '/assets/images/coffee-miel.jpg' },
  { id: 'tdpbhw371ps', label: 'Caffe Americano', price: 4.25, recipe: ['xfnu3t6igc', '9vcjpxckykd'], image: '/assets/images/caffe-americano.jpg' },
  { id: 'dezgcth6e8m', label: 'Macchiato', price: 5, recipe: ['stshpszygl', '9vcjpxckykd'], image: '/assets/images/macchiato.jpg' },
  { id: 'jo2om78gc0e', label: 'Long Black', price: 4.25, recipe: ['xfnu3t6igc', '9vcjpxckykd'], image: '/assets/images/long-black.jpg' },
  { id: 'hkx3o6l16lw', label: 'Vienna Coffee', price: 7, recipe: ['2p03cnu269d', '9vcjpxckykd'], image: '/assets/images/vienna-coffee.jpg' },
  { id: 'on0imhenyxl', label: 'Coffee Cortado', price: 5, recipe: ['wt5sp7nkwph', '9vcjpxckykd'], image: '/assets/images/coffee-cortado.jpeg' },
  { id: 'wqzzqbc2xok', label: 'Coffee con Hielo', price: 4.5, recipe: ['9vcjpxckykd', 'ym6w0tn0mq'], image: '/assets/images/cafe-con-hielo.jpg' },
  { id: 'rmaqhuywlza', label: 'Coffee Au Lait', price: 5, recipe: ['wl2u7001i5j', 'mrkz9n38qe'], image: '/assets/images/cafe-au-lait.jpg' },
  { id: '9mfwx4y451w', label: 'Espresso', price: 4, recipe: ['9vcjpxckykd'], image: '/assets/images/espresso.jpg' }
]

export const INGREDIENTS_ARR = [
  { id: 'imdcwgj7vcm', label: 'Chocolate Syrup', price: 3, category: 'extra' },
  { id: 'stshpszygl', label: 'Milk Foam', price: 1, category: 'milk' },
  { id: 'wl2u7001i5j', label: 'Steamed Milk', price: 1, category: 'milk' },
  { id: 'wt5sp7nkwph', label: 'Foamed Milk', price: 1, category: 'milk' },
  { id: 'p96tbt8ot8', label: 'Sweetened Condensed Milk', price: 2, category: 'milk' },
  { id: '2p03cnu269d', label: 'Whipped Cream', price: 3, category: 'extra' },
  { id: '6v5dx6muodj', label: 'Ice Cream', price: 3, category: 'extra' },
  { id: 'sf0zq2d35xk', label: 'Half & Half', price: 1, category: 'milk' },
  { id: 'qz8lkb66q2o', label: 'Milk', price: 1, category: 'milk' },
  { id: 'gnrrej15t3a', label: 'Cinnamon', price: 0.5, category: 'extra' },
  { id: '8cak2bnj3wg', label: 'Honey', price: 1.5, category: 'extra' },
  { id: '9vcjpxckykd', label: 'Espresso', price: 4, category: 'coffee' },
  { id: 'mrkz9n38qe', label: 'Black Coffee', price: 4, category: 'coffee' },
  { id: 'ym6w0tn0mq', label: 'Ice Cubes', price: 0.5, category: 'extra' },
  { id: 'xfnu3t6igc', label: 'Hot Water', price: 0.25, category: 'extra' }
]

export const STOCK = {
  imdcwgj7vcm: 100,
  stshpszygl: 100,
  wl2u7001i5j: 100,
  wt5sp7nkwph: 100,
  p96tbt8ot8: 100,
  '2p03cnu269d': 100,
  '6v5dx6muodj': 100,
  sf0zq2d35xk: 100,
  qz8lkb66q2o: 100,
  gnrrej15t3a: 100,
  '8cak2bnj3wg': 100,
  '9vcjpxckykd': 100,
  mrkz9n38qe: 100,
  ym6w0tn0mq: 100,
  xfnu3t6igc: 100,
  kg10yda77k: 10,
  '3f51447su0z': 10,
  lm1poqe7rnk: 10,
  r6li6vtbcv: 10,
  '3xztjvoo1xp': 10,
  rpfv8zrmz3: 10,
  sebm1fgjqs9: 10,
  skp4fyyqyo: 10,
  quujtda2adl: 10,
  tdpbhw371ps: 10,
  dezgcth6e8m: 10,
  jo2om78gc0e: 10,
  hkx3o6l16lw: 10,
  on0imhenyxl: 10,
  wqzzqbc2xok: 10,
  rmaqhuywlza: 10,
  '9mfwx4y451w': 10
}
